server:
  port: ${port:9001}
  
logging:
  level:
    org.springframework: ERROR
    com.felipemello: DEBUG
    
spring:
  devtools:
    restart:
      enabled: true  
  data:
    mongodb:
       uri: ${uri:mongodb+srv://<username>:<password>@mflix-jho7e.mongodb.net/test?retryWrites=true&w=majority}  
       database: ${database:test}